version: "3.9"
services:
  db:
    image: postgres:16
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: todo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: todo_backend
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "3001:3001"

volumes:
  pgdata:
